version: 0.2
phases:
  install:
    commands:
      - echo "Installing Node.js 18.15.0"
      - curl -fsSL https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.gz | tar -xzC /usr/local --strip-components=1
      - echo "Node.js version:"
      - node -v
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: build